name: rhino-pkg-git
'on':
- workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - distro: ubuntu-latest
          architecture: all
    steps:
    - name: Init
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install -y jq rclone
    - name: Set up SSH key
      run: |
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H "${{ secrets.SSH_IP }}" >> ~/.ssh/known_hosts
    - name: Package
      run: |
        mkdir -p out && cd out
        m_name="rhino-pkg-git"
        m_dist="${{ matrix.distro }}"
        m_arch="${{ matrix.architecture }}"
        ../scripts/packer.sh "${m_name}" "${m_dist}" "${m_arch}"
        debfile=(*${m_arch}.deb)
        echo "DEBNAME=${debfile}" >> $GITHUB_ENV
    - name: Upload .deb files
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.DEBNAME }}@${{ matrix.distro }}
        path: out/${{ env.DEBNAME }}
    - name: Transfer files to the server
      run: |
        LOCATION="${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }}"
        DISTROPATH="/home/${{ secrets.SSH_USER }}/get/${{ matrix.architecture }}"
        scp -i ~/.ssh/id_ed25519 ./out/"${{ env.DEBNAME }}" "${LOCATION}:${DISTROPATH}"
